# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConvertVid < Formula
  desc "A fast CLI tool for converting video files between different formats"
  homepage "https://github.com/vib795/convert-video-formats"
  version "1.0.15"
  license "MIT"

  depends_on "ffmpeg" => :runtime

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vib795/convert-video-formats/releases/download/v1.0.15/convert-video-formats_1.0.15_darwin_amd64.tar.gz"
      sha256 "4f25cb5ae57bbbe199ce7c2836853e343ee3d9484ff795dca3587625d0c6bd70"

      def install
        bin.install "convert-vid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vib795/convert-video-formats/releases/download/v1.0.15/convert-video-formats_1.0.15_darwin_arm64.tar.gz"
      sha256 "e2784fb427b921fb3de811213379c4f55a9c6ca520dab2d2601acfe9e2bba187"

      def install
        bin.install "convert-vid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vib795/convert-video-formats/releases/download/v1.0.15/convert-video-formats_1.0.15_linux_amd64.tar.gz"
      sha256 "09b898a1420876eb1a769c04e79524106d37fa4fd716310ded5da90e4f6138b2"
      def install
        bin.install "convert-vid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vib795/convert-video-formats/releases/download/v1.0.15/convert-video-formats_1.0.15_linux_arm64.tar.gz"
      sha256 "3257f1ccaf11ed3995149f28bd7ad67495ccb96b28d69a0380017d883d3e4c28"
      def install
        bin.install "convert-vid"
      end
    end
  end

  test do
    system "#{bin}/convert-vid", "version"
  end
end
