# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConvertVid < Formula
  desc "A fast CLI tool for converting video files between different formats"
  homepage "https://github.com/vib795/convert-video-formats"
  version "1.0.15"
  license "MIT"

  depends_on "ffmpeg" => :runtime

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vib795/convert-video-formats/releases/download/v1.0.15/convert-video-formats_1.0.15_darwin_amd64.tar.gz"
      sha256 "a9848c0a43b948b2c4faeb7a0035f56d4c9522c89965573f53899dcf56e6f4cf"

      def install
        bin.install "convert-vid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vib795/convert-video-formats/releases/download/v1.0.15/convert-video-formats_1.0.15_darwin_arm64.tar.gz"
      sha256 "6c51a604441d1d9e8b8f52fbf4d717edf6d153ef0e33d68121300b8a5ea165f3"

      def install
        bin.install "convert-vid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vib795/convert-video-formats/releases/download/v1.0.15/convert-video-formats_1.0.15_linux_amd64.tar.gz"
      sha256 "9f42b1ec9676622c067504bb0a2d62a1256fedffa373a8a568a9a2b992010fcb"
      def install
        bin.install "convert-vid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vib795/convert-video-formats/releases/download/v1.0.15/convert-video-formats_1.0.15_linux_arm64.tar.gz"
      sha256 "cfd95729cad248c3a194731f1a4ea3bda4df4c4142c7deb901a81c65ff763a37"
      def install
        bin.install "convert-vid"
      end
    end
  end

  test do
    system "#{bin}/convert-vid", "version"
  end
end
